
services:
  mariadb_esonero:
    image: mariadb:11.7.2-ubi9
    container_name: mariadb_esonero
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=esonero
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql  # Mappatura del volume persistente
      - ./mariadb_init:/docker-entrypoint-initdb.d  # Cartella per script SQL iniziali
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=rootpassword"] 
      interval: 15s
      timeout: 30s
      retries: 5
    networks:
      - mariadb_network
    
  
  
  server_esonero:
    build: ./backend
    ports: 
     - "8003:8003"
    container_name: server_esonero
    depends_on:
      mariadb_esonero:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"] #preso dalla documentazione di health check
      interval: 15s
      timeout: 30s
      retries: 5
    networks:
      - mariadb_network

  cilent_esonero:
    build: ./frontend
    ports:
      - "8001:8001"
    container_name: cilent_esonero
    depends_on:
      server_esonero:
        condition: service_healthy
    networks:
      - mariadb_network



networks:
  mariadb_network:
    driver: bridge


  
